apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverapi
  template:
    metadata:
      labels:
        app: serverapi
    spec:
      containers:
        - name: serverapi
          image: tanujsde/serverapi:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_HOST
              value: "mongodb"
            - name: MONGODB_PORT
              value: "27017"
          imagePullPolicy: Always